
## Тест

Напишіть клас Fraction, конструктор якого приймає чисельник і знаменник. Якщо користувач передав в якості знаменника  `0`, то генеруйте виняток типу std::runtime_error (який знаходиться в заголовку stdexcept). У функції main() попросіть користувача ввести два цілих числа. Якщо числа, які ввів користувач, коректні, то виводьте створений об’єкт класу Fraction. Якщо ж числа некоректні, то ви повинні обробити виняток типу std::exception і повідомити користувачеві, що він ввів некоректні дані.

**_Підказка_:**  std::runtime_error є дочірнім класу-винятку std::exception, тому у вас повинен бути тільки один блок catch.

Приклад виконання програми:

`Enter the numerator: 7  
Enter the denominator: 0  
Your fraction has an invalid denominator.`